#!/usr/bin/env Rscript

library(tdmsreader)
library(eodplotter)
library(ggplot2)

suppressPackageStartupMessages(library("optparse"))
parser <- OptionParser()
parser <- add_option(parser, c("-f", "--file"), help="TDMS file input")
parser <- add_option(parser, c("-v", "--verbose"), help="Print verbose output")
parser <- add_option(parser, c("-c", "--channel"), help="Channel name")
parser <- add_option(parser, c("-s", "--start"), type="double", help="Start time")
parser <- add_option(parser, c("-e", "--end"), type="double", help="End time")

options = commandArgs(trailingOnly = TRUE)
opts = parse_args(parser, args = options)

if (is.null(opts$file)) {
    print_help(parser)
}

if (!file.exists(opts$file)) {
    stop('File not found')
}

plotTdms(opts$file, opts$channel, opts$start, opts$end)
ggsave(paste0(basename(opts$file), '.signal.png'), width=20)
