#!/usr/bin/env Rscript

library(tdmsreader)
suppressPackageStartupMessages(library("optparse"))
parser <- OptionParser()
parser <- add_option(parser, c("-f", "--file"), help="TDMS file input")
parser <- add_option(parser, c("-v", "--verbose"), help="Print verbose output")
parser <- add_option(parser, c("-c", "--channel"), help="Channel name")
parser <- add_option(parser, c("-s", "--start"), type="double", help="Start time")
parser <- add_option(parser, c("-e", "--end"), type="double", help="End time")
parser <- add_option(parser, c("-o", "--out"), help="Output png")

options = commandArgs(trailingOnly = TRUE)
opts = parse_args(parser, args = options)

if (is.null(opts$file) || is.null(opts$out)) {
    print_help(parser)
}

if (!file.exists(opts$tdms)) {
    stop('File not found')
}

png(opts$out, width=2000, height=900)
plot(opts$filename, opts$channel, opts$start, opts$end)
dev.off()
